### PR TITLE
RFC: adopt JSF bylaws as the baseline

### PR DESCRIPTION
**Pull request by rubys**
Preface
-------

Because we don't yet have either a complete set of requirements or a process by which proposals can be evaluated, a few words up front to prevent misunderstandings:

This is meant as **A** proposal, not necessarily the only proposal.  The original author of this proposal has no special authority.  The purpose of this effort is to identify a concrete proposal that can be evaluated, and that evaluation can lead to either proposed changes or to the creation of alternatives.

Proposal
--------

Have the merged foundation adopt the existing JS Foundation bylaws as is, and thereby treat one or more of Node.js, Express, and libuv as new projects.

Process thoughts
----------------

Since we don't have an approved process yet for evaluating RFCs, I propose that this get discussion here on nodejs/bootstrap, be added to the agenda for the [weekly merge sub-committee meeting](https://github.com/nodejs/bootstrap/issues/10) on Monday October 22, and if there aren't any objections by the subsequent weekly meeting on the 29th, that it be adopted as a baseline for further changes.

If there are objections, we should work with those raising objections to either propose changes or alternatives (including proposing no foundation merge at all).  If no such work progresses in the period between weekly merge committee meetings, then the objection will be treated as invalid.

Motivation
----------

The primary starting point of this is to propose the simplest thing that could possibly work.

Beyond that, an observation is that the JS Foundation is essentially a loosely coupled federation of projects (and would like to keep it that way), and the Node.js Foundation is a comparitively tightly focused organization, and would seek to keep independence so as to continue to pursue this focus.

Also, looking at the bylaws, it is quite possible to position Node.js, et. al. as examples of "key JavaScript solutions and related technologies", whereas the converse is not true, i.e., positioning existing JSF Projects as part of the Node.js "Platform".

Summary of impact
-----------------

Note: these impacts are for the proposal as is; any or all of them can be addressed by proposing changes.

Overall:

* The existing foundation will acquire new members, Directors, and staff.  Some of the overap will need to be resolved (e.g., Chair/President, two primary locations, Directors from the same corporation and/or subsidiary of a parent company).
* Someone will need to verify that the exception to Federal taxes that the JS Foundation obtained is not affected by this transaction.
* Most significantly, there is no TSC or ConCom in the JSF bylaws.  The question to be explored is whether these can be rechartered as Project committees instead of Board committees - keeping with the idea of project independence and loose coupling.
 * The opportunity exists for Node.js and/or Express and/or libuv to get project seats on the JSF TAC.

Other, less significant, impacts (primarily to the Node.js foundation):

* Node.js loses its Individual ("non-voting") member on the board, as well as Community Committee Director and TSC Director.  These functions would be "pushed down" to the project(s).
* Node.js board loses its ability to approve (and thereby reject) associate entities from joining the board.
* Node.js term limits will not be a part of the bylaws
* Gold and Silver members get individual votes
* Loss of "good standing" bylaws language
* Loss of "super-majority" requirement to change IP rules

Supporting arguments
--------------------

Unabashedly cherry picked from...

 From https://github.com/nodejs/bootstrap/issues/5

* I _do_ know I don't want lots of onerous new processes
* make sure that not only the largest projects have a voice

From https://github.com/nodejs/bootstrap/issues/11

* By-laws general enough not to require evolution
* Simple, project-driven governance evolution
* Projects make all technical decisions
* Make projects feel like a priority
* Project Independence
* Goal: Minimum Viable Foundation to vote on and move to
* Perfect is the enemy of done

From https://github.com/nodejs/bootstrap/pull/9

* As above, the "small core" philosophy applies as much to the Governance model
as it does to the code.
* Possible loss of focus
* Projects want to preserve autonomous governance
* Projects want to maintain independent presence
* Projects want ability to exist in foundation without additional politics

For completeness, there are a number of inputs that this proposal does NOT address, most notably from https://github.com/nodejs/bootstrap/pull/6

### CODE REVIEW

**Comment by jorydotcom** [comment]
I like this idea as a jumping off point, primarily because the JSF bylaws are just a bit simpler.  After reviewing your [HTML diff](https://intertwingly.net/tmp/bylaws-diff.html) there are changes I would propose, though. What's the best way to iterate on or suggest a counter approach on some sections?

**Comment by jasnell** [comment]
I'll have to take time over the next couple of days to respond on this properly but my initial reaction is a definite -1 to jumping to this right away. We have already been hearing over the past few days about significant breakdowns in communication within the jsf structure. Projects feeling disengaged, unclear processes, metrics, and so on. We should seek to understand this more before jumping immediately to selecting a baseline set of bylaws.

I'd much rather see us spend time focusing more on why we're doing all this in the first place. Gather the guiding principles, goals, acknowledge the concerns, etc. This is jumping right in to selecting the right shade of blue to paint our boat when it's really still not clear what it is we're trying to accomplish.

**Comment by rubys** [comment]
@jorydotcom: the reason I posted the bylaws in markdown format is to make it easier to propose and track changes.  You can fork my repository and create pull requests against my rfc_adopt_JSF_bylaws branch.

@jasnell: what evidence do you have the the problems you are hearing about (and to be clear: I have every reason to believe that they are valid problems) are a result of bugs in the bylaws?  Having done a very thorough review of the bylaws, the differences are minor.

Without a baseline, we will be spinning our wheels.  

I can definitely see arguments for and against a merger.  What I can't see is an argument to leave both foundations in limbo (making, for example, hiring a permanent ED difficult) for an extended period of time.  This will affect everything from marketing to fundraising.  This will not be good for the ecosystem.

I didn't create this problem.  You didn't create this problem.  But it needs to be addressed.

My recommendation is that we start from where we are and iterate.

What would you propose we use as a baseline?  I don't believe that starting from a blank slate and applying a waterfall approach is a recipe for success.

I look forward to your proposal(s).

**Comment by rubys** [comment]
@jasnell perhaps a phone call is in order.

There is a lot of work to be done.  Working on bylaws is an area that nobody (to my knowledge) is working on.

I strongly believe that doing everything serially and without a clear schedule is not a recipe for success.

Resolving the differences between the bylaws is a substantial piece of work.

Goals can be defined/refined in parallel (and, I will note that process can (and should!) continue well after this hypothetical merger) takes place.  As goals are defined (or changed), it would be helpful to have a baseline for bylaws to compare them against in order to generate patches.

If you look at the bylaws for both organizations, it is clear that they both came from a common baseline.  Nobody creates a foundation without bylaws.  And absolutely nobody comes up with bylaws starting from a clean slate.

My ask is that you don't block this work without a specific problem that needs to be addressed.

**Comment by MylesBorins** [comment]
Perhaps the Monday call with board members and reps from both foundation
communities could be a good place to sort out a starting place and reach
consensus?

**Comment by rubys** [comment]
@MylesBorins I plan to be there!  And the "Process thoughts" section of this pull request explicitly requests that this be on the agenda.  :-)  Please make it so.

My style is not to come into such a discussion empty handed.  I would much rather come in with a concrete proposal and/or demonstration of substantial progress.  Worst case, some or all of my work is thrown away, but I can live with that.

**Comment by jorydotcom** [comment]
@jasnell I hear you, but that analogy isn't quite right for me. The bylaws aren't about shades of paint - they're about type of structure (e.g. apartment building vs. office park). There's nothing in either Node or JSF's bylaws that would have solved the communication issues on either side - that has to be solved by the descriptions and expectations of Directorship or officer roles, for example, as well as the scope of the board and any of its board committees. 

If I understand correctly, the point you're bringing is that there may be some mis-alignment on the $FOUNDATION's purpose and core values, which I agree would inevitably cascade into the issues we experienced on both sides; is that right?

**Comment by jorydotcom** [comment]
@jasnell I hear you, but that analogy isn't quite right for me. The bylaws aren't about shades of paint - they're about type of structure (e.g. apartment building vs. office park). There's nothing in either Node or JSF's bylaws that would have solved the communication issues on either side - that has to be solved by the descriptions and expectations of Directorship or officer roles, for example, as well as the scope of the board and any of its board committees.

If I understand correctly, the point you're bringing is that there may be some mis-alignment on the $FOUNDATION's purpose and core values, which I agree would inevitably cascade into the issues we experienced on both sides; is that right?

**Comment by dylans** [comment]
@jasnell , I pretty much agree with @jorydotcom and @MylesBorins on this, there is really nothing in the bylaws that would have addressed the concerns and issues raised or anything that prevents the feedback from being addressed. It is arguable that having board representation for the projects is something that the Node.js foundation has which the JS Foundation did not have, and maybe should have. The argument against it is that the typical things that the board discusses would not be of direct interest to most of the projects, which leads to that member getting bored of being on the board, pun intended.

**Comment by mhdawson** [comment]
I'm also in agreement that starting with something concrete to discuss makes sense to me.  We seem to have agreement that we don't want to start from a blank slate so starting with one of the 2 existing ones and then iterating from there makes sense to me.

@jasnell I can understand you'd like to focus on something different to start but I don't think that other people who are interested in work on this part should have to wait.

Answering the questions you are focussed on might mean that the early work on the bylaws might need to be thrown out, but provided that's understood I don't see that asking people not to work on them is in alignment with our usual approach to contributions.

**Comment by mcollina** [comment]
I think for the projects having board representation is non-negotiable. I’m also very surprised to see this point being mentioned as “of limited impact”.

Node.js had a significant amount of drama that lead to the Foundation being created in the first place. The relationship between the project and the Foundation has always been “Trust, but verify” - what this proposal is asking for removes that critical part. I cannot be anything but -1 on any proposal that did not allow for project representation on the board.

I think that closer relationship with the Board enabled the project, and it did not constrain it. The travel budget and the collaborator summits are direct results of this collaboration. We heard our directors telling us “what can the Foundation do for the project” and we listened.
I expect all of this to diminish without the project participation on the Board, because we would lack a strong voice to advocate for those things - and those are budget decisions.

**Comment by rubys** [comment]
@mcollina I gather that your experience is with an activist board.  if so, that's a shame.  I will tell you that that's not the only or best model.  Nor one that works well with three dozen projects (let alone [hundreds](https://projects.apache.org/)).  In any case, this pull request isn't about making a final decision on what the bylaws look like, it is about creating a baseline upon which changes can be proposed.  My suggestion is that if we are going to explore what a merged foundation looks like (which will have over 30 projects) the result will look more like the JSF than it will differ from it.  If we start from there, an issue could be immediately opened to determine what project representation would look like.

**Comment by mcollina** [comment]
@rubys I’m sorry for stating some known stuff, but it is also for other people reading this. The Node.js project did not ask for this merger to happen. This is a decision by the Boards. 
The Node.js project is thriving on the current setup, and we are struggling to find tactical problems that this merger would solve.

Node.js has very little say on the matter, as the Board can ratify this without a TSC/CommComm involvement. Even if we disagreed on the matter, Node.js cannot leave the Foundation because of the agreements on its copyright: the only possibility would be a fork. As such, the best interest of the project is to guarantee a successful merge according to _some_ criteria.

Stating that, and the history of the Node.js project, removing project representation on the board sounds like a power grab, not in the best interest of the project, thus totally against the current values of the Node.js Foundation. So, why doing the merger in the first place?

I'd kindly ask @MylesBorins and @hackygolucky to clarify if they think their role is important for the project. I did not understand that _removing the project directors_ was on the goals for the merger.

---

I agree that a merged foundation would look similar to the loosely coupled federation of projects that the JSF currently is. So, instead of _adopting the JSF bylaws as is_, we could use that structure as a starting point.

I'm sorry to steer the conversation on the most controversial point. However I think it's really important that we crack that open. __Do we want Board representation?__ This is possibly worth an issue on its own.

**Comment by mcollina** [comment]
@rubys I’m sorry for stating some known stuff, but it is also for other people reading this. The Node.js project did not ask for this merger to happen. This is a decision by the Boards. 
The Node.js project is thriving on the current setup, and we are struggling to find tactical problems that this merger would solve.

Node.js has very little say on the matter, as the Board can ratify this without a TSC/CommComm involvement. Even if we disagreed on the matter, Node.js cannot leave the Foundation because of the agreements on its copyright: the only possibility would be a fork. As such, the best interest of the project is to guarantee a successful merge according to _some_ criteria.

Stating that, and the history of the Node.js project, removing project representation on the board sounds like a power grab, not in the best interest of the project, thus totally against the current values of the Node.js Foundation. So, why doing the merger in the first place?

I'd kindly ask @MylesBorins and @hackygolucky to clarify if they think their role is important for the project. I did not understand that _removing the project directors_ was on the goals for the merger.

---

I agree that a merged foundation would look similar to the loosely coupled federation of projects that the JSF currently is. So, instead of _adopting the JSF bylaws as is_, we could use that structure as a starting point.

I'm sorry to steer the conversation on the most controversial point. However I think it's really important that we crack that open. __Do we want Board representation?__ This is possibly worth an issue on its own.

**Comment by mcollina** [comment]
@rubys I’m sorry for stating some known stuff, but it is also for other people reading this. The Node.js project did not ask for this merger to happen. This is a decision by the Boards. 
The Node.js project is thriving on the current setup, and we are struggling to find tactical problems that this merger would solve.

Node.js has very little say on the matter, as the Board can ratify this without a TSC/CommComm involvement. Even if we disagreed on the matter, Node.js cannot leave the Foundation because of the agreements on its copyright: the only possibility would be a fork. As such, the best interest of the project is to guarantee a successful merge according to _some_ criteria.

Stating that, and the history of the Node.js project, removing project representation on the board sounds like a power grab, not in the best interest of the project, thus totally against the current values of the Node.js Foundation. So, why doing the merger in the first place?

I'd kindly ask @MylesBorins and @hackygolucky to clarify if they think their role is important for the project. I did not understand that _removing the project directors_ was on the goals for the merger.

---

I agree that a merged foundation would look similar to the loosely coupled federation of projects that the JSF currently is. So, instead of _adopting the JSF bylaws as is_, we could use that structure as a starting point.

I'm sorry to steer the conversation on the most controversial point. However I think it's really important that we crack that open. __Do we want Board representation?__ This is possibly worth an issue on its own.

**Comment by mcollina** [comment]
@rubys I’m sorry for stating some known stuff, but it is also for other people reading this. The Node.js project did not ask for this merger to happen. This is a decision by the two Boards. 
The Node.js project is thriving on the current setup, and we are struggling to find tactical problems that this merger would solve.

Node.js has very little say on the matter, as the Board can ratify this without a TSC/CommComm involvement. Even if we disagreed on the matter, Node.js cannot leave the Foundation because of the agreements on its copyright: the only possibility would be a fork. As such, the best interest of the project is to guarantee a successful merge according to _some_ criteria.

Stating that, and the history of the Node.js project, removing project representation on the board sounds like a power grab, not in the best interest of the project, thus totally against the current values of the Node.js Foundation. So, why doing the merger in the first place?

I'd kindly ask @MylesBorins and @hackygolucky to clarify if they think their role is important for the project. I did not understand that _removing the project directors_ was on the list of goals for the merger.

---

I agree that a merged foundation would look similar to the loosely coupled federation of projects that the JSF currently is. So, instead of _adopting the JSF bylaws as is_, we could use that structure as a starting point.

I'm sorry to steer the conversation on the most controversial point. However I think it's really important that we crack that open. __Do we want Board representation?__ This is possibly worth an issue on its own.

**Comment by mcollina** [comment]
@rubys I’m sorry for stating some known stuff, but it is also for other people reading this. The Node.js project did not ask for this merger to happen. This is a decision by the two Boards. 
The Node.js project is thriving on the current setup, and we are struggling to find tactical problems that this merger would solve.

Node.js has very little say on the matter, as the Board can ratify this without a TSC/CommComm involvement. Even if we disagreed on the matter, Node.js cannot leave the Foundation because of the agreements on its copyright: the only possibility would be a fork. As such, the best interest of the project is to guarantee a successful merge according to _some_ criteria.

Stating that, and the history of the Node.js project, removing project representation on the board sounds like a power grab, not in the best interest of the project, thus totally against the current values of the Node.js Foundation. So, why doing the merger in the first place?

I'd kindly ask @MylesBorins and @hackygolucky to clarify if they think their role is important for the project. I did not understand that _removing the project directors_ was on the list of goals for the merger.

---

I agree that a merged foundation would look similar to the loosely coupled federation of projects that the JSF currently is. So, instead of _adopting the JSF bylaws as is_, we could use that structure as a starting point.

I'm sorry to steer the conversation on the most controversial point. However I think it's really important that we crack that open. __Do we want Board representation?__ This is possibly worth an issue on its own.

**Comment by jasnell** [comment]
Reaching for a specific set of existing bylaws as a starting point when we don't even yet have agreement around the specific set of problems we're trying to solve for is not overly helpful. Yes, the comparison of the two sets of bylaws is helpful in understanding the structural and on-paper operational differences between the two organizations but it does not really help us determine the right starting point.

The simplest thing that could possibly work is making no change to the existing bylaws at all and keeping the two Foundations separate.

We have an existing set of bylaws *already* so my counter proposal is that we start from there as the baseline and iterate from there.

**Comment by rubys** [comment]
For now, I'm going to operate under the a working assumption that the goal of a bootstrapping effort is to describe what a potential merged foundation would look like.

**Comment by rubys** [comment]
Superseded by https://github.com/nodejs/bootstrap/pull/27

**Pull request closed without merging**
