### PR TITLE
doc: add responsibility for charter review

### PR DESCRIPTION
**Pull request by mhdawson**

### CODE REVIEW

**Comment by mhdawson** [comment]
@MylesBorins I think this the update needed based on what was discussed in the last meeting.

**Comment by MylesBorins** [comment]
@mhdawson do you want to replace $FOUNDATION with OpenJS Foundation as part of this PR?

**Comment by MylesBorins** [comment]
This change has also already been reviewed by the board and we can move forward with stage 3 as long as we have community consensus around this language

**Comment by mhdawson** [comment]
@MylesBorins, will upate the $FOUNDATION sections

**Comment by mhdawson** [comment]
@MylesBorins pushed commit to update name of Foundation.

**Pull request merged**
